(function(){'use strict';
function E(id){return document.getElementById(id)}
function show(id){document.querySelectorAll('.screen').forEach(function(s){s.classList.remove('active')});var s=E(id);if(s)s.classList.add('active');window.scrollTo(0,0)}
function rand(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function card(text,fn,cls,sub){var b=document.createElement('button');b.type='button';b.className=cls||'grade';b.innerHTML='<b>'+text+'</b><span>'+(sub||'Seleccionar')+'</span>';b.onclick=function(e){e.preventDefault();e.stopPropagation();fn()};return b}
var quickGrade=1,quickDiff=1,quickList=[],quickPos=0,quickScore=0;
function qmake(g){var a=rand(2,8+g*3),b=rand(2,7+g*2),type=rand(1,4),text,ans;if(g<=2){if(type<3){text=a+' + '+b+' = ?';ans=a+b}else{text=(a+b)+' − '+a+' = ?';ans=b}}else if(g<=5){if(type<3){text=a+' × '+b+' = ?';ans=a*b}else{text=(a*b)+' ÷ '+a+' = ?';ans=b}}else if(g<=8){if(type===1){text='2x + '+a+' = '+(a+2*b)+' → x = ?';ans=b}else if(type===2){text='Área: '+a+' × '+b+' = ?';ans=a*b}else{text='3x = '+(a*3)+' → x = ?';ans=a}}else{if(type===1){text='√'+(a*a)+' = ?';ans=a}else if(type===2){text='2^'+(a%5)+' × 2^'+(b%4)+' = ?';ans=Math.pow(2,(a%5)+(b%4))}else{text='f(x)=x²+'+b+'; f('+a+') = ?';ans=a*a+b}}return {text:text,answer:String(ans)}}
function uniqueQ(g,n){var out=[],seen={};while(out.length<n){var q=qmake(g);if(!seen[q.text+'|'+q.answer]){seen[q.text+'|'+q.answer]=1;out.push(q)}}return out}
function quickGrades(){var box=E('quickGradeGrid');if(!box)return;box.innerHTML='';for(var g=1;g<=11;g++){(function(g){box.appendChild(card('⚡ '+g+'° grado',function(){quickGrade=g;quickDiffScreen()},'grade','Elige dificultad'))})(g)}show('quickChallenges')}
function quickDiffScreen(){var box=E('quickGradeGrid');if(!box)return;box.innerHTML='<h3 style="grid-column:1/-1">⚡ '+quickGrade+'° grado — dificultad</h3>';[['🌱 Inicial',1],['⚡ Intermedia',2],['🔥 Avanzada',3]].forEach(function(x){box.appendChild(card(x[0],function(){quickDiff=x[1];startQuick()},'difficulty-card','12 preguntas nuevas'))});box.appendChild(card('← Grados',quickGrades,'back','Volver'))}
function startQuick(){quickList=uniqueQ(quickGrade,12);quickPos=0;quickScore=0;show('quickGame');drawQuick()}
function drawQuick(){var q=quickList[quickPos],box=E('quickOptions'),fb=E('quickFeedback'),next=E('quickNext');E('quickTitle').textContent='⚡ '+quickGrade+'° grado';E('quickInfo').textContent=['','Inicial','Intermedia','Avanzada'][quickDiff];E('quickProgress').textContent='Pregunta '+(quickPos+1)+' de 12 · '+quickScore+' aciertos';E('quickQuestion').textContent=q.text;fb.textContent='';next.style.display='none';box.innerHTML='';var vals=[Number(q.answer),Number(q.answer)+rand(1,7),Number(q.answer)-rand(1,7),Number(q.answer)+rand(8,15)];vals.sort(function(){return Math.random()-.5});vals.forEach(function(v){var b=card(String(v),function(){box.querySelectorAll('button').forEach(function(x){x.disabled=true});if(String(v)===q.answer){quickScore++;fb.textContent='✅ ¡Correcto!'}else fb.textContent='❌ La respuesta era '+q.answer;next.textContent=quickPos===11?'🏁 Finalizar':'➡️ Siguiente';next.style.display='inline-block'},'answer','');box.appendChild(b)});next.onclick=function(){if(quickPos<11){quickPos++;drawQuick()}else{fb.textContent='🏁 Resultado: '+quickScore+'/12';next.style.display='none'}}}
var mentalGrade=1,mentalDiff=1,mentalNums=[],mentalSum=0,mentalTimer=null;
function mentalGrades(){var box=E('mentalGradeGrid');if(!box)return;box.innerHTML='';for(var g=1;g<=11;g++){(function(g){box.appendChild(card('🧠 '+g+'° grado',function(){mentalGrade=g;mentalDiffScreen()},'grade','Elige dificultad'))})(g)}show('mental')}
function mentalDiffScreen(){var box=E('mentalGradeGrid');box.innerHTML='<h3 style="grid-column:1/-1">🧠 '+mentalGrade+'° grado — dificultad</h3>';[['🌱 Inicial',1],['⚡ Intermedia',2],['🔥 Avanzada',3]].forEach(function(x){box.appendChild(card(x[0],function(){mentalDiff=x[1];startMental()},'difficulty-card','Serie diferente cada vez'))});box.appendChild(card('← Grados',mentalGrades,'back','Volver'))}
function startMental(){clearTimeout(mentalTimer);var count=Math.min(8,3+Math.floor((mentalGrade-1)/2)+mentalDiff),max=mentalGrade<=2?9+mentalGrade*3:mentalGrade<=6?20+mentalGrade*5:40+mentalGrade*8;mentalNums=[];while(mentalNums.length<count){var n=rand(1,max);if(mentalNums.indexOf(n)<0)mentalNums.push(n)}mentalSum=mentalNums.reduce(function(a,b){return a+b},0);show('mentalGame');E('mentalTitle').textContent='🧠 '+mentalGrade+'° grado';E('mentalInfo').textContent='Dificultad: '+['','Inicial','Intermedia','Avanzada'][mentalDiff];E('mentalSequence').textContent='';E('mentalQuestion').textContent='👀 Memoriza la serie';E('mentalFeedback').textContent='';E('mentalAnswer').style.display='none';E('mentalCheck').style.display='none';var i=0;function tick(){if(i>=mentalNums.length){E('mentalSequence').textContent='❓';E('mentalQuestion').textContent='¿Cuál es la suma total?';E('mentalAnswer').value='';E('mentalAnswer').style.display='block';E('mentalCheck').style.display='inline-block';return}E('mentalSequence').textContent=mentalNums[i++];mentalTimer=setTimeout(tick,Math.max(450,900-mentalDiff*100-mentalGrade*15))}tick()}
function checkMental(){var ok=Number(E('mentalAnswer').value)===mentalSum;E('mentalFeedback').textContent=ok?'✅ ¡Correcto!':'❌ La respuesta era '+mentalSum;E('mentalCheck').style.display='none'}
function wire(){document.querySelectorAll('.category-card').forEach(function(b){b.onclick=function(e){e.preventDefault();e.stopPropagation();var k=b.getAttribute('data-category');if(k==='quick')quickGrades();else if(k==='mental')mentalGrades()}});if(E('quickGradeGrid'))quickGrades();if(E('mentalGradeGrid'))mentalGrades();var qe=E('quickNext');if(qe)qe.type='button';var me=E('mentalCheck');if(me){me.type='button';me.onclick=function(e){e.preventDefault();checkMental()}}var backs=[['backExplore','home'],['backQuick','explore'],['backMental','explore'],['backQuickGame','quickChallenges'],['backMentalGame','mental']];backs.forEach(function(x){var b=E(x[0]);if(b)b.onclick=function(e){e.preventDefault();e.stopPropagation();show(x[1])}});var ex=E('exploreBtn');if(ex)ex.onclick=function(e){e.preventDefault();show('explore')}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
})();