(function(){'use strict';
function E(id){return document.getElementById(id)}
function show(id){document.querySelectorAll('.screen').forEach(function(s){s.classList.remove('active')});var s=E(id);if(s)s.classList.add('active');window.scrollTo(0,0)}
function rand(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function card(text,fn,cls,sub){var b=document.createElement('button');b.type='button';b.className=cls||'grade';b.innerHTML='<b>'+text+'</b><span>'+(sub||'Seleccionar')+'</span>';b.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();fn()});return b}
function qmake(g){var a=rand(2,8+g*3),b=rand(2,7+g*2),type=rand(1,4),text,ans;if(g<=2){if(type<3){text=a+' + '+b+' = ?';ans=a+b}else{text=(a+b)+' − '+a+' = ?';ans=b}}else if(g<=5){if(type<3){text=a+' × '+b+' = ?';ans=a*b}else{text=(a*b)+' ÷ '+a+' = ?';ans=b}}else if(g<=8){if(type===1){text='2x + '+a+' = '+(a+2*b)+' → x = ?';ans=b}else if(type===2){text='Área: '+a+' × '+b+' = ?';ans=a*b}else{text='3x = '+(a*3)+' → x = ?';ans=a}}else{if(type===1){text='√'+(a*a)+' = ?';ans=a}else if(type===2){text='2^'+(a%5)+' × 2^'+(b%4)+' = ?';ans=Math.pow(2,(a%5)+(b%4))}else{text='f(x)=x²+'+b+'; f('+a+') = ?';ans=a*a+b}}return{text:text,answer:String(ans)}}
function uniqueQ(g,n){var out=[],seen={};while(out.length<n){var q=qmake(g);if(!seen[q.text+'|'+q.answer]){seen[q.text+'|'+q.answer]=1;out.push(q)}}return out}
function removeUnstableSections(){['quickChallenges','quickGame','mental','mentalGame'].forEach(function(id){var s=E(id);if(s)s.remove()});document.querySelectorAll('.category-card[data-category="quick"],.category-card[data-category="mental"]').forEach(function(b){b.remove()})}
var challengeGrade=1,challengeList=[],challengePos=0,challengeScore=0;
function ensureChallengeScreen(){if(E('challengeGrades'))return;var s=document.createElement('section');s.id='challengeGrades';s.className='screen';s.innerHTML='<button id="backChallenge" class="back">← Inicio</button><div class="hero explore-head"><h2>⚡ Desafíos</h2><p>Elige tu grado y completa 10 preguntas.</p></div><div id="challengeGradeGrid" class="grid"></div>';document.querySelector('main').appendChild(s);E('backChallenge').addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();show('home')},true);for(var g=1;g<=11;g++){(function(grade){E('challengeGradeGrid').appendChild(card('⚡ '+grade+'° grado',function(){challengeGrade=grade;startChallenge()},'grade','10 preguntas'))})(g)}}
function startChallenge(){challengeList=uniqueQ(challengeGrade,10);challengePos=0;challengeScore=0;var s=E('challengeGame');if(!s){s=document.createElement('section');s.id='challengeGame';s.className='screen';s.innerHTML='<button id="backChallengeGame" class="back">← Grados</button><div class="hero explore-head"><h2 id="challengeTitle"></h2><p id="challengeInfo"></p></div><div class="card"><div id="challengeProgress" class="progress"></div><div id="challengeQuestion" class="question"></div><div id="challengeOptions" class="answers"></div><p id="challengeFeedback" class="feedback"></p><button id="challengeNext" class="primary" style="display:none">Siguiente</button></div>';document.querySelector('main').appendChild(s);E('backChallengeGame').addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();show('challengeGrades')},true);E('challengeNext').addEventListener('click',nextChallenge,true)}show('challengeGame');drawChallenge()}
function drawChallenge(){var q=challengeList[challengePos],box=E('challengeOptions'),fb=E('challengeFeedback'),next=E('challengeNext');E('challengeTitle').textContent='⚡ Desafíos · '+challengeGrade+'° grado';E('challengeInfo').textContent='10 preguntas';E('challengeProgress').textContent='Pregunta '+(challengePos+1)+' de 10 · '+challengeScore+' aciertos';E('challengeQuestion').textContent=q.text;fb.textContent='';next.style.display='none';box.innerHTML='';var vals=[Number(q.answer),Number(q.answer)+rand(1,7),Number(q.answer)-rand(1,7),Number(q.answer)+rand(8,15)];vals.sort(function(){return Math.random()-.5});vals.forEach(function(v){box.appendChild(card(String(v),function(){box.querySelectorAll('button').forEach(function(x){x.disabled=true});if(String(v)===q.answer){challengeScore++;fb.textContent='✅ ¡Correcto!'}else fb.textContent='❌ La respuesta era '+q.answer;next.textContent=challengePos===9?'🏁 Finalizar':'➡️ Siguiente';next.style.display='inline-block'},'answer',''))})}
function nextChallenge(){if(challengePos<9){challengePos++;drawChallenge()}else{E('challengeFeedback').textContent='🏁 Resultado final: '+challengeScore+'/10';E('challengeNext').style.display='none'}}
var miniGrade=1,miniList=[],miniPos=0,miniScore=0;
function miniGrades(){var box=E('miniGradeGrid');if(!box){var s=document.createElement('section');s.id='miniGrades';s.className='screen';s.innerHTML='<button id="backMini" class="back">← Inicio</button><div class="hero"><h2>🎮 Minijuegos</h2><p>Elige tu grado y juega 5 rondas.</p></div><div id="miniGradeGrid" class="grid"></div>';document.querySelector('main').appendChild(s);box=E('miniGradeGrid');E('backMini').addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();show('home')},true)}box.innerHTML='';for(var g=1;g<=11;g++){(function(grade){box.appendChild(card('🎮 '+grade+'° grado',function(){miniGrade=grade;startMini()},'grade','5 rondas'))})(g)}show('miniGrades')}
function startMini(){miniList=uniqueQ(miniGrade,5);miniPos=0;miniScore=0;ensureMiniGame();show('miniGame');drawMini()}
function ensureMiniGame(){if(E('miniGame'))return;var s=document.createElement('section');s.id='miniGame';s.className='screen';s.innerHTML='<button id="backMiniGame" class="back">← Grados</button><div class="hero"><h2 id="miniTitle"></h2><p id="miniInfo"></p></div><div class="card"><div id="miniProgress" class="progress"></div><div id="miniQuestion" class="question"></div><div id="miniOptions" class="answers"></div><p id="miniFeedback" class="feedback"></p><button id="miniNext" class="primary" style="display:none">Siguiente</button></div>';document.querySelector('main').appendChild(s);E('backMiniGame').addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();show('miniGrades')},true);E('miniNext').addEventListener('click',nextMini,true)}
function drawMini(){var q=miniList[miniPos],box=E('miniOptions'),fb=E('miniFeedback'),next=E('miniNext');E('miniTitle').textContent='🎮 Minijuego · '+miniGrade+'° grado';E('miniInfo').textContent='5 rondas';E('miniProgress').textContent='Ronda '+(miniPos+1)+' de 5 · '+miniScore+' aciertos';E('miniQuestion').textContent=q.text;fb.textContent='';next.style.display='none';box.innerHTML='';var vals=[Number(q.answer),Number(q.answer)+rand(1,5),Number(q.answer)-rand(1,5),Number(q.answer)+rand(6,10)];vals.sort(function(){return Math.random()-.5});vals.forEach(function(v){box.appendChild(card(String(v),function(){box.querySelectorAll('button').forEach(function(x){x.disabled=true});if(String(v)===q.answer){miniScore++;fb.textContent='🎉 ¡Acertaste!'}else fb.textContent='❌ Era '+q.answer;next.textContent=miniPos===4?'🏁 Terminar':'➡️ Siguiente';next.style.display='inline-block'},'answer',''))})}
function nextMini(){if(miniPos<4){miniPos++;drawMini()}else{E('miniFeedback').textContent='🏆 Resultado: '+miniScore+'/5';E('miniNext').style.display='none'}}
var exploreCat='lab',exploreGrade=1,exploreClass=1,exploreDiff=1;
function exploreGrades(cat){exploreCat=cat||'lab';var box=E('exploreGradeGrid');if(!box)return;E('exploreGradesTitle').textContent='📚 '+exploreName(exploreCat);E('exploreGradesInfo').textContent='Elige un grado para continuar';box.innerHTML='';for(var g=1;g<=11;g++){(function(g){box.appendChild(card('🎓 '+g+'° grado',function(){exploreGrade=g;exploreClasses()},'grade','Entrar'))})(g)}show('exploreGrades')}
function exploreName(c){return c==='lab'?'Laboratorio Matemático':c==='puzzle'?'Rompecabezas':c==='build'?'Construye tu mundo':'Explorar'}
function exploreClasses(){var box=E('exploreClassGrid');if(!box)return;E('exploreClassesTitle').textContent=exploreName(exploreCat)+' · '+exploreGrade+'°';E('exploreClassesInfo').textContent='Elige una clase';box.innerHTML='';var names=exploreCat==='lab'?['Fracciones visuales','Medidas','Áreas y perímetros','Gráficas']:exploreCat==='puzzle'?['Patrones','Lógica','Geometría','Probabilidad']:['Figuras','Coordenadas','Perímetros','Construcción'];names.forEach(function(n,i){box.appendChild(card('📘 '+n,function(){exploreClass=i+1;exploreDifficulty()},'class-card','Ver dificultades'))});box.appendChild(card('← Grados',function(){exploreGrades(exploreCat)},'back','Volver'));show('exploreClasses')}
function exploreDifficulty(){var box=E('exploreDifficultyGrid');if(!box)return;E('exploreDifficultyTitle').textContent='Clase '+exploreClass+' · '+exploreGrade+'° grado';E('exploreDifficultyInfo').textContent='Elige dificultad';box.innerHTML='';[['🌱 Inicial',1],['⚡ Intermedia',2],['🔥 Avanzada',3]].forEach(function(x){box.appendChild(card(x[0],function(){exploreDiff=x[1];startLesson()},'difficulty-card','Entrar')});box.appendChild(card('← Clases',exploreClasses,'back','Volver'));show('exploreDifficulty')}
function startLesson(){var q=uniqueQ(exploreGrade,1)[0],box=E('lessonOptions');show('exploreLesson');E('exploreLessonTitle').textContent=exploreName(exploreCat)+' · '+exploreGrade+'°';E('exploreLessonInfo').textContent='Clase '+exploreClass+' · '+['','Inicial','Intermedia','Avanzada'][exploreDiff];E('lessonQuestion').textContent=q.text;E('lessonFeedback').textContent='';box.innerHTML='';var vals=[Number(q.answer),Number(q.answer)+1,Number(q.answer)-1,Number(q.answer)+2];vals.forEach(function(v){box.appendChild(card(String(v),function(){box.querySelectorAll('button').forEach(function(x){x.disabled=true});E('lessonFeedback').textContent=String(v)===q.answer?'✅ ¡Correcto!':'❌ Respuesta: '+q.answer},'answer',''))})}
function goHome(e){if(e){e.preventDefault();e.stopImmediatePropagation()}show('home');return false}
function wire(){removeUnstableSections();ensureChallengeScreen();var back=E('backExplore');if(back){back.type='button';back.addEventListener('click',goHome,true)}var ex=E('exploreBtn');if(ex){ex.type='button';ex.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();show('explore')},true)}var games=E('gamesBtn');if(games){games.type='button';games.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();miniGrades()},true)}var challenges=E('challengeBtn');if(challenges){challenges.type='button';challenges.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();show('challengeGrades')},true)}document.querySelectorAll('.category-card').forEach(function(b){b.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();var c=b.getAttribute('data-category');if(c==='lab'||c==='puzzle'||c==='build')exploreGrades(c)},true)});var map=[['backExploreGrades','explore'],['backExploreClasses','exploreGrades'],['backExploreDifficulty','exploreClasses'],['backExploreLesson','exploreDifficulty']];map.forEach(function(x){var b=E(x[0]);if(b)b.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();show(x[1])},true)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
})();
