(function(){'use strict';
function E(id){return document.getElementById(id)}
function show(id){document.querySelectorAll('.screen').forEach(function(s){s.classList.remove('active')});var s=E(id);if(s)s.classList.add('active');window.scrollTo(0,0)}
function rand(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function card(text,fn,cls,sub){var b=document.createElement('button');b.type='button';b.className=cls||'grade';b.innerHTML='<b>'+text+'</b><span>'+(sub||'Seleccionar')+'</span>';b.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();fn()});return b}
function qmake(g,d){d=d||1;var a=rand(2,8+g+d*3),b=rand(2,7+g+d*2),type=rand(1,4),text,ans;if(g<=2){text=type<3?a+' + '+b+' = ?':(a+b)+' − '+a+' = ?';ans=type<3?a+b:b}else if(g<=5){text=type<3?a+' × '+b+' = ?':(a*b)+' ÷ '+a+' = ?';ans=type<3?a*b:b}else if(g<=8){if(type===1){text='2x + '+a+' = '+(a+2*b)+' → x = ?';ans=b}else if(type===2){text='Área: '+a+' × '+b+' = ?';ans=a*b}else{text='3x = '+(a*3)+' → x = ?';ans=a}}else{if(type===1){text='√'+(a*a)+' = ?';ans=a}else if(type===2){text='2^'+(a%5)+' × 2^'+(b%4)+' = ?';ans=Math.pow(2,(a%5)+(b%4))}else{text='f(x)=x²+'+b+'; f('+a+') = ?';ans=a*a+b}}return{text:text,answer:String(ans)}}
function uniqueQ(g,n,d){var out=[],seen={};while(out.length<n){var q=qmake(g,d);if(!seen[q.text+'|'+q.answer]){seen[q.text+'|'+q.answer]=1;out.push(q)}}return out}
function removeUnstableSections(){['quickChallenges','quickGame','mental','mentalGame'].forEach(function(id){var s=E(id);if(s)s.remove()});document.querySelectorAll('.category-card[data-category="quick"],.category-card[data-category="mental"]').forEach(function(b){b.remove()})}
var challengeGrade=1,challengeList=[],challengePos=0,challengeScore=0,challengeTimer=null,challengeTimeLeft=60;
function stopChallengeTimer(){if(challengeTimer){clearInterval(challengeTimer);challengeTimer=null}}
function ensureChallengeScreen(){if(E('challengeGrades'))return;var s=document.createElement('section');s.id='challengeGrades';s.className='screen';s.innerHTML='<button id="backChallenge" class="back" type="button">← Inicio</button><div class="hero explore-head"><h2>⚡ Desafíos</h2><p>Elige tu grado. Cada nivel dura 60 segundos.</p></div><div id="challengeGradeGrid" class="grid"></div>';document.querySelector('main').appendChild(s);s.querySelector('#backChallenge').addEventListener('click',goHome,true);for(var g=1;g<=11;g++){(function(grade){E('challengeGradeGrid').appendChild(card('⚡ '+grade+'° grado',function(){challengeGrade=grade;startChallenge()},'grade','60 segundos · dificultad progresiva'))})(g)}}
function startChallenge(){stopChallengeTimer();challengeList=[];for(var d=1;d<=4;d++)challengeList=challengeList.concat(uniqueQ(challengeGrade,3,d));challengePos=0;challengeScore=0;challengeTimeLeft=60;ensureChallengeGame();show('challengeGame');drawChallenge();startChallengeTimer()}
function startChallengeTimer(){stopChallengeTimer();challengeTimeLeft=60;updateChallengeTimer();challengeTimer=setInterval(function(){challengeTimeLeft--;updateChallengeTimer();if(challengeTimeLeft<=0){stopChallengeTimer();finishChallengeByTime()}},1000)}
function updateChallengeTimer(){var t=E('challengeTimer');if(t)t.textContent='⏱️ '+Math.max(0,challengeTimeLeft)+' s'}
function finishChallengeByTime(){var box=E('challengeOptions'),next=E('challengeNext'),fb=E('challengeFeedback');if(box)box.querySelectorAll('button').forEach(function(x){x.disabled=true});if(fb)fb.textContent='⏰ ¡Tiempo terminado! Resultado: '+challengeScore+'/12';if(next){next.style.display='inline-block';next.disabled=false;next.textContent='🏁 Finalizar';next.dataset.finished='1'}}
function ensureChallengeGame(){if(E('challengeGame'))return;var s=document.createElement('section');s.id='challengeGame';s.className='screen';s.innerHTML='<button id="backChallengeGame" class="back" type="button">← Grados</button><div class="hero explore-head"><h2 id="challengeTitle"></h2><p id="challengeInfo"></p></div><div class="card"><div id="challengeTimer" class="progress">⏱️ 60 s</div><div id="challengeProgress" class="progress"></div><div id="challengeQuestion" class="question"></div><div id="challengeOptions" class="answers"></div><p id="challengeFeedback" class="feedback"></p><button id="challengeNext" class="primary" type="button" style="display:none">Siguiente</button></div></div>';document.querySelector('main').appendChild(s);s.querySelector('#backChallengeGame').addEventListener('click',function(e){stopChallengeTimer();e.preventDefault();e.stopImmediatePropagation();show('challengeGrades')},true);s.querySelector('#challengeNext').addEventListener('click',nextChallenge,true)}
function drawChallenge(){var q=challengeList[challengePos],difficulty=Math.min(4,1+Math.floor(challengePos/3)),box=E('challengeOptions'),fb=E('challengeFeedback'),next=E('challengeNext');E('challengeTitle').textContent='⚡ Desafíos · '+challengeGrade+'° grado';E('challengeInfo').textContent='Dificultad '+difficulty+' · cada nivel dura 60 segundos';E('challengeProgress').textContent='Pregunta '+(challengePos+1)+' de 12 · '+challengeScore+' aciertos';E('challengeQuestion').textContent=q.text;fb.textContent='';next.style.display='none';next.disabled=true;next.dataset.finished='';box.innerHTML='';var ans=Number(q.answer),span=4+difficulty*2,vals=[ans,ans+rand(1,span),ans-rand(1,span),ans+rand(span+1,span+7)];var seen={};vals=vals.filter(function(v){if(seen[v])return false;seen[v]=1;return true});while(vals.length<4){var v=ans+rand(-12,12);if(!seen[v]){seen[v]=1;vals.push(v)}}vals.sort(function(){return Math.random()-.5});vals.forEach(function(v){box.appendChild(card(String(v),function(){if(!next.disabled)return;box.querySelectorAll('button').forEach(function(x){x.disabled=true});var ok=String(v)===q.answer;if(ok){challengeScore++;fb.textContent='✅ ¡Correcto!'}else fb.textContent='❌ La respuesta era '+q.answer;saveReward(ok,6,1);next.textContent=challengePos===11?'🏁 Finalizar':'➡️ Siguiente';next.disabled=false;next.style.display='inline-block'},'answer',''))})}
function nextChallenge(){if(E('challengeNext').disabled)return;if(E('challengeNext').dataset.finished==='1'||challengePos>=11){stopChallengeTimer();E('challengeFeedback').textContent='🏁 Resultado final: '+challengeScore+'/12';E('challengeNext').style.display='none';return}challengePos++;drawChallenge()}
var miniGrade=1,miniList=[],miniPos=0,miniScore=0;
function miniGrades(){var box=E('miniGradeGrid');if(!box){var s=document.createElement('section');s.id='miniGrades';s.className='screen';s.innerHTML='<button id="backMini" class="back" type="button">← Inicio</button><div class="hero"><h2>🎮 Minijuegos</h2><p>Elige tu grado. La dificultad cambia cada 2 rondas.</p></div><div id="miniGradeGrid" class="grid"></div>';document.querySelector('main').appendChild(s);box=E('miniGradeGrid');s.querySelector('#backMini').addEventListener('click',goHome,true)}box.innerHTML='';for(var g=1;g<=11;g++){(function(grade){box.appendChild(card('🎮 '+grade+'° grado',function(){miniGrade=grade;startMini()},'grade','10 rondas · XP y monedas'))})(g)}show('miniGrades')}
function startMini(){miniList=[];for(var d=1;d<=5;d++)miniList=miniList.concat(uniqueQ(miniGrade,2,d));miniPos=0;miniScore=0;ensureMiniGame();show('miniGame');drawMini()}
function ensureMiniGame(){if(E('miniGame'))return;var s=document.createElement('section');s.id='miniGame';s.className='screen';s.innerHTML='<button id="backMiniGame" class="back" type="button">← Grados</button><div class="hero"><h2 id="miniTitle"></h2><p id="miniInfo"></p></div><div class="card"><div id="miniProgress" class="progress"></div><div id="miniQuestion" class="question"></div><div id="miniOptions" class="answers"></div><p id="miniFeedback" class="feedback"></p><button id="miniNext" class="primary" type="button" style="display:none">Siguiente</button></div></div>';document.querySelector('main').appendChild(s);s.querySelector('#backMiniGame').addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();show('miniGrades')},true);s.querySelector('#miniNext').addEventListener('click',nextMini,true)}
function drawMini(){var q=miniList[miniPos],difficulty=Math.min(5,1+Math.floor(miniPos/2)),box=E('miniOptions'),fb=E('miniFeedback'),next=E('miniNext');E('miniTitle').textContent='🎮 Minijuego · '+miniGrade+'° grado';E('miniInfo').textContent='Dificultad '+difficulty+' · cambia cada 2 rondas';E('miniProgress').textContent='Ronda '+(miniPos+1)+' de 10 · '+miniScore+' aciertos';E('miniQuestion').textContent=q.text;fb.textContent='';next.style.display='none';next.disabled=true;box.innerHTML='';var ans=Number(q.answer),span=3+difficulty,vals=[ans,ans+rand(1,span),ans-rand(1,span),ans+rand(span+1,span+5)];var seen={};vals=vals.filter(function(v){if(seen[v])return false;seen[v]=1;return true});while(vals.length<4){var v=ans+rand(-10,10);if(!seen[v]){seen[v]=1;vals.push(v)}}vals.sort(function(){return Math.random()-.5});vals.forEach(function(v){box.appendChild(card(String(v),function(){if(!next.disabled)return;box.querySelectorAll('button').forEach(function(x){x.disabled=true});var ok=String(v)===q.answer;if(ok){miniScore++;fb.textContent='🎉 ¡Acertaste!'}else fb.textContent='❌ Era '+q.answer;saveReward(ok,4,1);next.textContent=miniPos===9?'🏁 Terminar':'➡️ Siguiente';next.disabled=false;next.style.display='inline-block'},'answer',''))})}
function nextMini(){if(E('miniNext').disabled)return;if(miniPos<9){miniPos++;drawMini()}else{E('miniFeedback').textContent='🏆 Resultado: '+miniScore+'/10';E('miniNext').style.display='none'}}
function saveReward(ok,xp,coins){try{var s=JSON.parse(localStorage.getItem('aventuraMatematica')||'{}');s.xp=(s.xp||0)+(ok?xp:0);s.coins=(s.coins||0)+(ok?coins:0);localStorage.setItem('aventuraMatematica',JSON.stringify(s));if(typeof update==='function')update()}catch(e){}}
var exploreCat='lab',exploreGrade=1,exploreClass=1,exploreDiff=1;
function exploreGrades(cat){exploreCat=cat||'lab';var box=E('exploreGradeGrid');if(!box)return;E('exploreGradesTitle').textContent='📚 '+exploreName(exploreCat);E('exploreGradesInfo').textContent='Elige un grado para continuar';box.innerHTML='';for(var g=1;g<=11;g++){(function(g){box.appendChild(card('🎓 '+g+'° grado',function(){exploreGrade=g;exploreClasses()},'grade','Entrar'))})(g)}show('exploreGrades')}
function exploreName(c){return c==='lab'?'Laboratorio Matemático':c==='puzzle'?'Rompecabezas':c==='build'?'Construye tu mundo':'Explorar'}
function exploreClasses(){var box=E('exploreClassGrid');if(!box)return;E('exploreClassesTitle').textContent=exploreName(exploreCat)+' · '+exploreGrade+'°';E('exploreClassesInfo').textContent='Elige una clase';box.innerHTML='';var names=exploreCat==='lab'?['Fracciones visuales','Medidas','Áreas y perímetros','Gráficas']:exploreCat==='puzzle'?['Patrones','Lógica','Geometría','Probabilidad']:['Figuras','Coordenadas','Perímetros','Construcción'];names.forEach(function(n,i){box.appendChild(card('📘 '+n,function(){exploreClass=i+1;exploreDifficulty()},'class-card','Ver dificultades'))});box.appendChild(card('← Grados',function(){exploreGrades(exploreCat)},'back','Volver'));show('exploreClasses')}
function exploreDifficulty(){var box=E('exploreDifficultyGrid');if(!box)return;E('exploreDifficultyTitle').textContent='Clase '+exploreClass+' · '+exploreGrade+'° grado';E('exploreDifficultyInfo').textContent='Elige dificultad';box.innerHTML='';[['🌱 Inicial',1],['⚡ Intermedia',2],['🔥 Avanzada',3]].forEach(function(x){box.appendChild(card(x[0],function(){exploreDiff=x[1];startLesson()},'difficulty-card','Entrar'))});box.appendChild(card('← Clases',exploreClasses,'back','Volver'));show('exploreDifficulty')}
function startLesson(){var q=uniqueQ(exploreGrade,1)[0],box=E('lessonOptions');show('exploreLesson');E('exploreLessonTitle').textContent=exploreName(exploreCat)+' · '+exploreGrade+'°';E('exploreLessonInfo').textContent='Clase '+exploreClass+' · '+['','Inicial','Intermedia','Avanzada'][exploreDiff];E('lessonQuestion').textContent=q.text;E('lessonFeedback').textContent='';box.innerHTML='';var vals=[Number(q.answer),Number(q.answer)+1,Number(q.answer)-1,Number(q.answer)+2];vals.forEach(function(v){box.appendChild(card(String(v),function(){box.querySelectorAll('button').forEach(function(x){x.disabled=true});E('lessonFeedback').textContent=String(v)===q.answer?'✅ ¡Correcto!':'❌ Respuesta: '+q.answer},'answer',''))})}
function goHome(e){if(e){e.preventDefault();e.stopImmediatePropagation();e.stopPropagation()}stopChallengeTimer();show('home');return false}
function wire(){removeUnstableSections();ensureChallengeScreen();document.querySelectorAll('button.back').forEach(function(back){var label=(back.textContent||'').trim();if(label.indexOf('Inicio')!==-1){back.type='button';back.addEventListener('click',goHome,true)}});var back=E('backExplore');if(back){back.type='button';back.addEventListener('click',goHome,true)}var ex=E('exploreBtn');if(ex){ex.type='button';ex.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();show('explore')},true)}var games=E('gamesBtn');if(games){games.type='button';games.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();miniGrades()},true)}var challenges=E('challengeBtn');if(challenges){challenges.type='button';challenges.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();show('challengeGrades')},true)}document.querySelectorAll('.category-card').forEach(function(b){b.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();var c=b.getAttribute('data-category');if(c==='lab'||c==='puzzle'||c==='build')exploreGrades(c)},true)});var map=[['backExploreGrades','explore'],['backExploreClasses','exploreGrades'],['backExploreDifficulty','exploreClasses'],['backExploreLesson','exploreDifficulty']];map.forEach(function(x){var b=E(x[0]);if(b)b.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();show(x[1])},true)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
})();