from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
if 'data-fix="stable-interaction-v3"' in s:
    raise SystemExit(0)
fix=r'''<script data-fix="stable-interaction-v3">(function(){'use strict';
var F={grade:1,level:1,pos:0,qs:[],score:0,quickGrade:1,quickDiff:0,quickPos:0,quickQs:[],quickScore:0,mentalGrade:1,mentalDiff:0,mentalSeq:[],mentalAns:0};
function q$(id){return document.getElementById(id)}function fshow(id){document.querySelectorAll('.screen').forEach(function(x){x.classList.remove('active')});var e=q$(id);if(e)e.classList.add('active');window.scrollTo(0,0)}
function frand(a,b){return Math.floor(Math.random()*(b-a+1))+a}function fload(){try{var x=JSON.parse(localStorage.getItem('aventuraMatematica')||'null');return x&&typeof x==='object'?x:{}}catch(e){return {}}}function fsave(x){try{localStorage.setItem('aventuraMatematica',JSON.stringify(x))}catch(e){}}
var FS=fload();FS.completed=FS.completed||{};FS.questionHistory=Array.isArray(FS.questionHistory)?FS.questionHistory:[];FS.world=Array.isArray(FS.world)?FS.world:[];
function fsaveState(){fsave(FS);if(typeof update==='function')update()}
function fmake(text,ans){var o=[ans],span=Math.max(2,Math.ceil(Math.abs(ans)*.18));while(o.length<4){var n=Number((ans+frand(-span,span)).toFixed(2));if(o.indexOf(n)<0)o.push(n)}o.sort(function(){return Math.random()-.5});return{text:text,answer:String(ans),options:o.map(String)}}
function funiq(gen,n){var out=[],tries=0;while(out.length<n&&tries<n*1200){var q=gen(),k=q.text+'|'+q.answer;if(FS.questionHistory.indexOf(k)<0){FS.questionHistory.push(k);out.push(q)}tries++}return out}
function fq(g,d){var a=frand(2,12+g+d*5),b=frand(2,10+g+d*4),p=frand(2,7);if(g===1)return fmake(a+' + '+b+' = ?',a+b);if(g===2)return fmake(a+' − '+b+' = ?',a-b);if(g===3)return d<3?fmake(a+' × '+b+' = ?',a*b):fmake((a*b)+' ÷ '+a+' = ?',b);if(g===4)return d===1?fmake(a+' × '+b+' = ?',a*b):d===2?fmake('Perímetro de cuadrado lado '+a+' = ?',4*a):d===3?fmake('Área de rectángulo '+a+' × '+b+' = ?',a*b):fmake('¿Qué fracción de '+a*4+' es '+a+'?',.25);if(g===5)return d===1?fmake((a/10).toFixed(1)+' + '+(b/10).toFixed(1)+' = ?',Number(((a+b)/10).toFixed(1))):d===2?fmake('25% de '+a*4+' = ?',a):fmake('Proporción: 3 cuestan '+a*3+'. 5 cuestan ?',a*5/3);if(g===6)return d===1?fmake('20% de '+a*5+' = ?',a):d===2?fmake('MCM de '+a+' y '+b+' = ?',function(){var x=a,y=b;while(y){var t=x%y;x=y;y=t}return Math.abs(a*b/x)}()):fmake('2x + '+a+' = '+(a+b*2)+' → x = ?',b);if(g===7)return d===1?fmake('−'+a+' + '+b+' = ?',b-a):d===2?fmake('2x + '+a+' = '+(a+b*2)+' → x = ?',b):fmake('3(x − '+a+') = '+b*3+' → x = ?',a+b);if(g===8)return d===1?fmake('2(x + '+a+') = '+b*2+' → x = ?',b-a):d===2?fmake('x/2 + '+a+' = '+(a+b)+' → x = ?',2*b):fmake('Área triángulo base '+a+' y altura '+b+' = ?',a*b/2);if(g===9)return d===1?fmake('2^'+p+' × 2^'+b%5+' = ?',Math.pow(2,p+b%5)):d===2?fmake('√'+a*a+' = ?',a):fmake('f(x)=x²+'+a+'. f('+b+') = ?',b*b+a);if(g===10)return d===1?fmake('Pendiente entre (0,0) y ('+a+','+b+') = ?',b/a):d===2?fmake('x² − '+(a+b)+'x + '+a*b+' = 0. x menor = ?',Math.min(a,b)):fmake('Probabilidad '+a+' favorables de '+(a+b)+' = ?',a/(a+b));return d===1?fmake('Derivada de x² en x='+a+' = ?',2*a):d===2?fmake('∫2x dx en x='+a+' = ?',a*a):fmake('Límite en x='+a+' de (x²−'+a*a+')/(x−'+a+') = ?',2*a)}
function fgrades(){var h='';for(var g=1;g<=11;g++)h+='<button class="grade" data-fg="'+g+'"><b>📚 '+g+'° grado</b><span>11 grados · 10 niveles · 20 preguntas</span></button>';q$('grades').innerHTML=h;document.querySelectorAll('#grades .grade').forEach(function(b){b.onclick=function(){F.grade=+b.dataset.fg;flevels();fshow('levels')}})}
function flevels(){var h='';for(var l=1;l<=10;l++){var ok=l===1||!!FS.completed[F.grade+'-'+(l-1)],done=!!FS.completed[F.grade+'-'+l];h+='<button class="level" '+(ok?'':'disabled')+' data-fl="'+l+'"><b>'+(done?'✅ ':ok?'▶️ ':'🔒 ')+'Nivel '+l+'</b><span>'+ (done?'Completado':ok?'20 preguntas únicas':'Completa el anterior')+'</span></button>'}q$('levelGrid').innerHTML=h;q$('gradeTitle').textContent='Grado '+F.grade+'°';q$('gradeInfo').textContent='11 grados disponibles';document.querySelectorAll('#levelGrid .level:not(:disabled)').forEach(function(b){b.onclick=function(){F.level=+b.dataset.fl;F.pos=0;F.score=0;F.qs=funiq(function(){return fq(F.grade,Math.min(4,1+Math.floor((F.level-1)/2)))},20);fshow('quiz');frender()}})}
function frender(){var q=F.qs[F.pos];if(!q)return; q$('progress').textContent='Nivel '+F.level+' · Pregunta '+(F.pos+1)+' de 20';q$('question').textContent=q.text;q$('feedback').textContent='';q$('next').style.display='none';q$('answers').innerHTML=q.options.map(function(v){return '<button class="answer" data-fa="'+v+'">'+v+'</button>'}).join('');document.querySelectorAll('#answers .answer').forEach(function(b){b.onclick=function(){document.querySelectorAll('#answers .answer').forEach(function(x){x.disabled=true});var ok=b.dataset.fa===q.answer;if(ok){F.score++;FS.xp=(FS.xp||0)+10;FS.coins=(FS.coins||0)+2;FS.streak=(FS.streak||0)+1;q$('feedback').textContent='✅ Correcto'}else{FS.streak=0;q$('feedback').textContent='❌ Era '+q.answer}fsaveState();q$('next').style.display='block';q$('next').textContent=F.pos===19?'🏁 Terminar':'➡️ Siguiente'}}) }
function quickGrades(){var h='';for(var g=1;g<=11;g++)h+='<button class="grade" data-fqg="'+g+'"><b>⚡ '+g+'° grado</b><span>Inicial · Intermedia · Avanzada</span></button>';q$('quickGradeGrid').innerHTML=h;document.querySelectorAll('#quickGradeGrid .grade').forEach(function(b){b.onclick=function(){F.quickGrade=+b.dataset.fqg;quickDiff()}});fshow('quickChallenges')}
function quickDiff(){q$('quickDifficultyTitle').textContent='⚡ Retos rápidos · '+F.quickGrade+'°';q$('quickDifficultyGrid').innerHTML='';['🌱 Inicial','⚡ Intermedia','🔥 Avanzada'].forEach(function(t,i){var b=document.createElement('button');b.className='difficulty-card';b.innerHTML='<b>'+t+'</b><span>12 preguntas nuevas</span>';b.onclick=function(){F.quickDiff=i;F.quickPos=0;F.quickScore=0;F.quickQs=funiq(function(){return fq(F.quickGrade,i+1)},12);q$('quickGameTitle').textContent='⚡ '+F.quickGrade+'° · '+t;fshow('quickGame');quickRender()};q$('quickDifficultyGrid').appendChild(b)});fshow('quickDifficulty')}
function quickRender(){var q=F.quickQs[F.quickPos];q$('quickGameProgress').textContent='Pregunta '+(F.quickPos+1)+' de 12 · '+F.quickScore+' aciertos';q$('quickQuestion').textContent=q.text;q$('quickFeedback').textContent='';q$('quickNext').style.display='none';q$('quickOptions').innerHTML=q.options.map(function(v){return '<button class="answer" data-qv="'+v+'">'+v+'</button>'}).join('');document.querySelectorAll('#quickOptions .answer').forEach(function(b){b.onclick=function(){document.querySelectorAll('#quickOptions .answer').forEach(function(x){x.disabled=true});if(b.dataset.qv===q.answer){F.quickScore++;FS.xp=(FS.xp||0)+7;FS.coins=(FS.coins||0)+1;q$('quickFeedback').textContent='✅ Correcto'}else q$('quickFeedback').textContent='❌ Era '+q.answer;fsaveState();q$('quickNext').style.display='block'}})}
function mentalGrades(){var h='';for(var g=1;g<=11;g++)h+='<button class="grade" data-mg="'+g+'"><b>🧠 '+g+'° grado</b><span>Serie rápida · 3 dificultades</span></button>';q$('mentalGradeGrid').innerHTML=h;document.querySelectorAll('#mentalGradeGrid .grade').forEach(function(b){b.onclick=function(){F.mentalGrade=+b.dataset.mg;mentalDifficulty()}});fshow('mental')}
function mentalDifficulty(){q$('mentalGame').dataset.ready='';q$('mentalTitle').textContent='🧠 Cálculo mental · '+F.mentalGrade+'°';q$('mentalInfo').textContent='Elige dificultad';q$('mentalStatus').textContent='Selecciona: Inicial · Intermedia · Avanzada';q$('mentalSequence').textContent='';q$('mentalAnswer').style.display='none';q$('mentalCheck').style.display='none';q$('mentalStart').style.display='none';var box=q$('mentalGame');box.querySelector('.card').innerHTML='<div id="mentalStatus" class="progress">Elige dificultad</div><div class="difficulty-grid" id="mentalDiffGrid"></div><div id="mentalSequence" class="mini-big"></div><div id="mentalQuestion" class="question" style="display:none"></div><input id="mentalAnswer" class="input" style="display:none" inputmode="numeric" placeholder="Resultado"><button id="mentalCheck" class="primary" style="display:none">Comprobar</button><button id="mentalStart" class="primary" style="display:none">Nueva serie</button><p id="mentalFeedback" class="feedback"></p>';['🌱 Inicial','⚡ Intermedia','🔥 Avanzada'].forEach(function(t,i){var b=document.createElement('button');b.className='difficulty-card';b.innerHTML='<b>'+t+'</b><span>Serie diferente cada vez</span>';b.onclick=function(){F.mentalDiff=i;mentalStart()};q$('mentalDiffGrid').appendChild(b)});fshow('mentalGame')}
function mentalStart(){clearInterval(mentalTimer);var count=Math.min(8,3+Math.floor((F.mentalGrade-1)/2)+F.mentalDiff),max=F.mentalGrade<=2?9+F.mentalGrade*3:F.mentalGrade<=6?20+F.mentalGrade*5:40+F.mentalGrade*8,seq,key,tries=0;do{seq=[];while(seq.length<count){var n=frand(1,max);if(seq.indexOf(n)<0)seq.push(n)}key='MENTAL|'+F.mentalGrade+'|'+F.mentalDiff+'|'+seq.join(',');tries++}while(FS.questionHistory.indexOf(key)>=0&&tries<200);FS.questionHistory.push(key);F.mentalSeq=seq;F.mentalAns=seq.reduce(function(a,b){return a+b},0);fsaveState();q$('mentalTitle').textContent='🧠 '+F.mentalGrade+'° grado · '+['Inicial','Intermedia','Avanzada'][F.mentalDiff];q$('mentalStatus').textContent='Memoriza los números';q$('mentalSequence').textContent='';q$('mentalQuestion').style.display='none';q$('mentalAnswer').style.display='none';q$('mentalCheck').style.display='none';var i=0;function flash(){if(i>=seq.length){q$('mentalSequence').textContent='❓';q$('mentalStatus').textContent='Ahora calcula la suma';q$('mentalQuestion').style.display='block';q$('mentalQuestion').textContent='¿Cuál es el resultado?';q$('mentalAnswer').style.display='block';q$('mentalCheck').style.display='inline-block';q$('mentalCheck').onclick=function(){var ok=Number(q$('mentalAnswer').value)===F.mentalAns;q$('mentalFeedback').textContent=ok?'✅ Correcto: '+F.mentalAns:'❌ Era '+F.mentalAns;if(ok){FS.xp=(FS.xp||0)+15;FS.coins=(FS.coins||0)+3}fsaveState();q$('mentalCheck').style.display='none';q$('mentalStart').style.display='inline-block';q$('mentalStart').onclick=mentalStart;};return}q$('mentalSequence').textContent=seq[i++];setTimeout(flash,Math.max(320,850-F.mentalDiff*140-F.mentalGrade*18))}flash()}
function bind(){q$('exploreBtn').onclick=function(){fshow('explore')};q$('exploreNav').onclick=function(){fshow('explore')};q$('homeNav').onclick=function(){fgrades();fshow('home')};q$('backExplore').onclick=function(){fshow('home')};document.querySelectorAll('.category-card').forEach(function(b){b.onclick=function(){var c=b.dataset.category;if(c==='quick')quickGrades();else if(c==='mental')mentalGrades();else if(typeof exploreGrades==='function')exploreGrades(c)}});q$('challengeBtn').onclick=function(){if(typeof renderChallenges==='function')renderChallenges();fshow('challenge')};q$('gamesBtn').onclick=function(){if(typeof renderGames==='function')renderGames();fshow('games')};q$('profileBtn').onclick=function(){fshow('profile')};q$('quickNext').onclick=function(){if(F.quickPos===11){q$('quickFeedback').textContent='🏁 Terminaste: '+F.quickScore+'/12';FS.xp=(FS.xp||0)+F.quickScore*4;fsaveState()}else{F.quickPos++;quickRender()}};q$('backQuick').onclick=function(){quickGrades()};q$('backQuickGame').onclick=function(){quickDiff()};q$('backMental').onclick=function(){fshow('explore')};q$('backMentalGame').onclick=function(){mentalGrades()};q$('next').onclick=function(){F.pos++;if(F.pos>=20){FS.completed[F.grade+'-'+F.level]=true;FS.xp=(FS.xp||0)+50;fsaveState();fshow('levels');flevels()}else frender()};q$('saveName').onclick=function(){FS.name=q$('name').value.trim()||'Estudiante';fsaveState()};}
try{fgrades();bind();}catch(e){console.error('stable fix',e)}
})();</script>'''
s=s.replace('</body>',fix+'</body>',1)
p.write_text(s,encoding='utf-8')