from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
if 'data-fix="stable-interaction-v3"' in s and 'data-fix="quick-mental-v5"' not in s:
    fix=r'''<script data-fix="quick-mental-v5">(function(){'use strict';
var qh;
try{qh=JSON.parse(localStorage.getItem('aventuraMatematica')||'{}')}catch(e){qh={}}
qh.questionHistory=Array.isArray(qh.questionHistory)?qh.questionHistory:[];
function qmSave(){try{localStorage.setItem('aventuraMatematica',JSON.stringify(qh))}catch(e){}}
function qmShow(id){document.querySelectorAll('.screen').forEach(function(x){x.classList.remove('active')});var e=document.getElementById(id);if(e)e.classList.add('active');window.scrollTo(0,0)}
function qmRand(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function qmMake(text,ans){var o=[ans],span=Math.max(2,Math.ceil(Math.abs(ans)*.2)),tries=0;while(o.length<4&&tries<100){var n=Number((ans+qmRand(-span,span)).toFixed(2));if(o.indexOf(n)<0)o.push(n);tries++}o.sort(function(){return Math.random()-.5});return{text:text,answer:String(ans),options:o.map(String)}}
function qmQuestion(g,d){var a=qmRand(2,10+g+d*4),b=qmRand(2,9+g+d*3),c=qmRand(2,8+g),type=qmRand(1,5);if(g<=2){return type%2?qmMake(a+' + '+b+' = ?',a+b):qmMake((a+b)+' − '+a+' = ?',b)}if(g<=4){return type%2?qmMake(a+' × '+b+' = ?',a*b):qmMake((a*b)+' ÷ '+a+' = ?',b)}if(g<=6){if(type===1)return qmMake('20% de '+a*5+' = ?',a);if(type===2)return qmMake('Área de rectángulo '+a+' × '+b+' = ?',a*b);if(type===3)return qmMake('Perímetro de rectángulo '+a+' × '+b+' = ?',2*(a+b));return qmMake('3x = '+a*3+' → x = ?',a)}if(g<=8){if(type===1)return qmMake('2x + '+a+' = '+(a+2*b)+' → x = ?',b);if(type===2)return qmMake('3(x − '+a+') = '+b*3+' → x = ?',a+b);return qmMake('Área de triángulo '+a+' × '+b+' / 2 = ?',a*b/2)}if(g<=10){if(type===1)return qmMake('2^'+a%5+' × 2^'+b%5+' = ?',Math.pow(2,(a%5)+(b%5)));if(type===2)return qmMake('√'+a*a+' = ?',a);if(type===3)return qmMake('Pendiente entre (0,0) y ('+a+','+b+') = ?',b/a);return qmMake('f(x)=x²+'+c+'. f('+a+') = ?',a*a+c)}return type%2?qmMake('Derivada de x² en x='+a+' = ?',2*a):qmMake('Límite en x='+a+' de (x²−'+a*a+')/(x−'+a+') = ?',2*a)}
function qmUnique(g,d,n){var out=[],tries=0;while(out.length<n&&tries<n*2000){var q=qmQuestion(g,d),key=q.text+'|'+q.answer;if(qh.questionHistory.indexOf(key)<0){qh.questionHistory.push(key);out.push(q)}tries++}qmSave();return out}
var qGrade=1,qDiff=0,qPos=0,qScore=0,qList=[];
var quickScreen=document.querySelector('#quickChallenges'),quickGameScreen=document.querySelector('#quickGame'),quickGradesBox=quickScreen&&quickScreen.querySelector('#quickGradeGrid'),quickGameTitle=quickGameScreen&&quickGameScreen.querySelector('#quickTitle'),quickGameInfo=quickGameScreen&&quickGameScreen.querySelector('#quickInfo'),quickGameProgress=quickGameScreen&&quickGameScreen.querySelector('#quickProgress'),quickQuestion=quickGameScreen&&quickGameScreen.querySelector('#quickQuestion'),quickOptions=quickGameScreen&&quickGameScreen.querySelector('#quickOptions'),quickFeedback=quickGameScreen&&quickGameScreen.querySelector('#quickFeedback'),quickNext=quickGameScreen&&quickGameScreen.querySelector('#quickNext');
function renderQGrades(){if(!quickGradesBox)return;quickGradesBox.innerHTML='';for(var g=1;g<=11;g++){var b=document.createElement('button');b.className='grade';b.innerHTML='<b>⚡ '+g+'° grado</b><span>'+((window.GI&&GI[g-1])||'Matemáticas')+' · 3 dificultades · 12 retos</span>';b.onclick=function(){qGrade=+this.textContent.match(/\d+/)[0];renderQDiff()};quickGradesBox.appendChild(b)}qmShow('quickChallenges')}
function renderQDiff(){var box=document.getElementById('quickDifficultyGrid'),title=document.getElementById('quickDifficultyTitle');if(!box)return;if(title)title.textContent='⚡ Retos rápidos · '+qGrade+'° grado';box.innerHTML='';[['🌱 Inicial',1],['⚡ Intermedia',2],['🔥 Avanzada',3]].forEach(function(x){var b=document.createElement('button');b.className='difficulty-card';b.innerHTML='<b>'+x[0]+'</b><span>12 preguntas nuevas y sin repetir</span>';b.onclick=function(){qDiff=x[1];startQ()};box.appendChild(b)});qmShow('quickDifficulty')}
function startQ(){qPos=0;qScore=0;qList=qmUnique(qGrade,qDiff,12);if(!qList.length)return;quickGameTitle.textContent='⚡ '+qGrade+'° grado · '+['Inicial','Intermedia','Avanzada'][qDiff-1];quickGameInfo.textContent='12 preguntas únicas · dificultad adaptada';qmShow('quickGame');renderQ()}
function renderQ(){if(qPos>=qList.length){quickFeedback.textContent='🏁 Terminaste: '+qScore+'/12';return}var q=qList[qPos];quickGameProgress.textContent='Pregunta '+(qPos+1)+' de 12 · '+qScore+' aciertos';quickQuestion.textContent=q.text;quickFeedback.textContent='';quickNext.style.display='none';quickOptions.innerHTML=q.options.map(function(v){return '<button class="answer" data-qv="'+v+'">'+v+'</button>'}).join('');quickOptions.querySelectorAll('.answer').forEach(function(b){b.onclick=function(){quickOptions.querySelectorAll('.answer').forEach(function(x){x.disabled=true});if(b.dataset.qv===q.answer){qScore++;quickFeedback.textContent='✅ ¡Correcto!'}else{quickFeedback.textContent='❌ Era '+q.answer}try{var st=JSON.parse(localStorage.getItem('aventuraMatematica')||'{}');st.xp=(st.xp||0)+ (b.dataset.qv===q.answer?7:0);st.coins=(st.coins||0)+(b.dataset.qv===q.answer?1:0);localStorage.setItem('aventuraMatematica',JSON.stringify(st))}catch(e){}quickNext.style.display='block';quickNext.textContent=qPos===11?'🏁 Ver resultado':'➡️ Siguiente'}})})}
function nextQ(){if(qPos===11){quickFeedback.textContent='🏁 Resultado final: '+qScore+'/12';quickNext.style.display='none'}else{qPos++;renderQ()}}
var mentalRoot=document.getElementById('mentalMath'),mentalSetup=mentalRoot&&mentalRoot.querySelector('#mentalSetup'),mentalRound=mentalRoot&&mentalRoot.querySelector('#mentalRound'),mentalGradeBox=mentalRoot&&mentalRoot.querySelector('#mentalGradeGrid'),mentalCountdown=mentalRoot&&mentalRoot.querySelector('#mentalCountdown'),mentalSeqBox=mentalRoot&&mentalRoot.querySelector('#mentalSequence'),mentalAnsBox=mentalRoot&&mentalRoot.querySelector('#mentalAnswer'),mentalCheckBtn=mentalRoot&&mentalRoot.querySelector('#mentalCheck'),mentalFeedback=mentalRoot&&mentalRoot.querySelector('#mentalFeedback'),mentalNums=[],mentalAnswer=0,mentalTimer=null,mentalG=1,mentalD=1;
function renderMGrades(){if(!mentalGradeBox)return;mentalGradeBox.innerHTML='';for(var g=1;g<=11;g++){var b=document.createElement('button');b.className='grade';b.innerHTML='<b>🧠 '+g+'° grado</b><span>3 dificultades · serie diferente cada vez</span>';b.onclick=function(){mentalG=+this.textContent.match(/\d+/)[0];renderMDiff()};mentalGradeBox.appendChild(b)}qmShow('mentalMath')}
function renderMDiff(){if(!mentalSetup)return;mentalSetup.innerHTML='<h3>🧠 '+mentalG+'° grado</h3><p>Elige la dificultad</p><div class="difficulty-grid" id="qmMentalDiff"></div>';var box=mentalSetup.querySelector('#qmMentalDiff');[['🌱 Inicial',1],['⚡ Intermedia',2],['🔥 Avanzada',3]].forEach(function(x){var b=document.createElement('button');b.className='difficulty-card';b.innerHTML='<b>'+x[0]+'</b><span>Serie nueva cada vez</span>';b.onclick=function(){mentalD=x[1];startM()};box.appendChild(b)})}
function startM(){clearInterval(mentalTimer);var count=Math.min(8,3+Math.floor((mentalG-1)/2)+mentalD),max=mentalG<=2?9+mentalG*3:mentalG<=6?20+mentalG*5:40+mentalG*8,key,tries=0;do{mentalNums=[];while(mentalNums.length<count){var n=qmRand(1,max);if(mentalNums.indexOf(n)<0)mentalNums.push(n)}key='MENTAL|'+mentalG+'|'+mentalD+'|'+mentalNums.join(',');tries++}while(qh.questionHistory.indexOf(key)>=0&&tries<300);qh.questionHistory.push(key);qmSave();mentalAnswer=mentalNums.reduce(function(a,b){return a+b},0);mentalSetup.style.display='none';mentalRound.style.display='block';mentalAnsBox.value='';mentalAnsBox.style.display='none';mentalCheckBtn.style.display='none';mentalFeedback.textContent='';var i=0;mentalCountdown.textContent='👀 Memoriza';function flash(){if(i>=mentalNums.length){mentalSeqBox.textContent='❓';mentalCountdown.textContent='🧠 ¡Ahora calcula la suma!';mentalAnsBox.style.display='block';mentalCheckBtn.style.display='inline-block';return}mentalSeqBox.textContent=mentalNums[i++];mentalTimer=setTimeout(flash,Math.max(320,850-mentalD*130-mentalG*16))}flash()}
function checkM(){var ok=Number(mentalAnsBox.value)===mentalAnswer;mentalFeedback.textContent=ok?'✅ ¡Excelente! Resultado: '+mentalAnswer:'❌ Resultado correcto: '+mentalAnswer;try{var st=JSON.parse(localStorage.getItem('aventuraMatematica')||'{}');st.xp=(st.xp||0)+(ok?15:5);st.coins=(st.coins||0)+(ok?3:0);localStorage.setItem('aventuraMatematica',JSON.stringify(st))}catch(e){}mentalCheckBtn.style.display='none';var again=document.createElement('button');again.className='primary';again.textContent='🔁 Nueva serie';again.onclick=startM;mentalRound.appendChild(again)}
function bindQM(){var qb=document.getElementById('quickChallengesBtn'),mb=document.getElementById('mentalMathBtn');if(qb)qb.onclick=renderQGrades;if(mb)mb.onclick=renderMGrades;document.querySelectorAll('.category-card').forEach(function(b){b.onclick=function(){if(b.dataset.category==='quick')renderQGrades();else if(b.dataset.category==='mental')renderMGrades();else if(typeof exploreGrades==='function')exploreGrades(b.dataset.category)}});if(quickNext)quickNext.onclick=nextQ;var bq=quickScreen&&quickScreen.querySelector('#backQuick');if(bq)bq.onclick=function(){qmShow('explore')};var bq2=quickGameScreen&&quickGameScreen.querySelector('#backQuickGame');if(bq2)bq2.onclick=renderQDiff;var bm=mentalRoot&&mentalRoot.querySelector('#backMentalMath');if(bm)bm.onclick=function(){clearInterval(mentalTimer);if(mentalRound)mentalRound.style.display='none';if(mentalSetup){mentalSetup.style.display='block';renderMGrades()}qmShow('explore')};if(mentalCheckBtn)mentalCheckBtn.onclick=checkM;var oldMental=document.getElementById('mentalMath');if(oldMental)oldMental.querySelectorAll('.grade').forEach(function(){ });}
try{bindQM()}catch(e){console.error('quick mental v5',e)}
})();</script>'''
    s=s.replace('</body>',fix+'</body>',1)
p.write_text(s,encoding='utf-8')