from pathlib import Path
p=Path('index.html');s=p.read_text(encoding='utf-8')
if 'quickChallengesBtn' in s: raise SystemExit('already integrated')
html='''<div class="card" style="border:2px solid #f59e0b"><h3>⚡ Retos rápidos y 🧠 Cálculo mental</h3><p>Nuevas actividades adaptadas a cada grado y dificultad.</p><div class="explore-toolbar"><button id="quickChallengesBtn" class="primary">⚡ Retos rápidos</button><button id="mentalMathBtn" class="primary">🧠 Cálculo mental</button></div></div><section id="quickChallenges" class="screen"><button id="backQuickChallenges" class="back">← Explorar</button><div class="hero explore-head"><h2>⚡ Retos rápidos</h2><p>Elige grado y dificultad. Cada partida crea 12 preguntas distintas.</p></div><div id="quickGradeGrid" class="grid"></div></section><section id="quickDifficulty" class="screen"><button id="backQuickDifficulty" class="back">← Retos rápidos</button><div class="hero explore-head"><h2 id="quickDifficultyTitle"></h2></div><div id="quickDifficultyGrid" class="difficulty-grid"></div></section><section id="quickGame" class="screen"><button id="backQuickGame" class="back">← Dificultades</button><div class="hero explore-head"><h2 id="quickGameTitle"></h2><p id="quickGameProgress"></p></div><div class="card"><div id="quickQuestion" class="question"></div><div id="quickOptions" class="answers"></div><p id="quickFeedback" class="feedback"></p><button id="quickNext" class="primary" style="display:none">Siguiente</button></div></section><section id="mentalMath" class="screen"><button id="backMentalMath" class="back">← Explorar</button><div class="hero explore-head"><h2>🧠 Cálculo mental</h2><p>Memoriza los números que aparecen rápidamente y luego calcula la suma.</p></div><div class="card mini-board"><div id="mentalSetup"><div id="mentalGradeGrid" class="grid"></div></div><div id="mentalRound" style="display:none"><div id="mentalCountdown" class="timer">👀 Prepárate…</div><div id="mentalSequence" class="mini-big"></div><input id="mentalAnswer" class="input" inputmode="numeric" placeholder="Escribe el resultado"><button id="mentalCheck" class="primary">Comprobar</button><p id="mentalFeedback" class="feedback"></p></div></div></section>'''
s=s.replace('</main>',html+'</main>',1)
js=r'''var quickGrade=1,quickDiff=0,quickPos=0,quickScore=0,quickQs=[],mentalGrade=1,mentalNumbers=[],mentalTimer=null;
function qmake(g,d,n){var a=(n*7+g*3+d*5)%18+2,b=(n*11+g*5+d*7)%15+2,ans,text;if(g<=2){ans=n%2?a+b:a-b;text=a+(n%2?' + ':' − ')+b+' = ?'}else if(g<=4){ans=n%2?a*b:a+b;text=(n%2?a+' × '+b:a+' + '+b)+' = ?'}else if(g<=8){ans=d===0?b:d===1?a:a+b;text=d===0?'2x = '+b*2+' → x = ?':d===1?'x + '+a+' = '+(a+b)+' → x = ?':'x − '+a+' = '+b+' → x = ?'}else{ans=d===0?a*a:d===1?a*b:2*a;text=d===0?a+'² = ?':d===1?a+' × '+b+' = ?':'Derivada de x² en x='+a+' = ?'}var o=[ans],k=2;while(o.length<4){var z=ans+(n+o.length)*k%7-3;if(o.indexOf(z)<0)o.push(z);k++}return{text:text,answer:String(ans),options:o.map(String),key:g+'-'+d+'-'+n}}
function renderQuickGrades(){var h='';for(var g=1;g<=11;g++)h+='<button class="grade" data-g="'+g+'"><b>⚡ '+g+'° grado</b><span>'+GI[g-1]+' · 3 dificultades</span></button>';$('quickGradeGrid').innerHTML=h;document.querySelectorAll('#quickGradeGrid .grade').forEach(function(b){b.onclick=function(){quickGrade=+b.dataset.g;renderQuickDiff()}});show('quickChallenges')}
function renderQuickDiff(){$('quickDifficultyTitle').textContent='⚡ Retos rápidos · '+quickGrade+'°';$('quickDifficultyGrid').innerHTML='';DIFF.forEach(function(x,i){var b=document.createElement('button');b.className='difficulty-card';b.innerHTML='<b>'+x[0]+'</b><span>'+x[1]+'</span><span>12 retos sin repetir</span>';b.onclick=function(){quickDiff=i;startQuick()};$('quickDifficultyGrid').appendChild(b)});show('quickDifficulty')}
function startQuick(){quickPos=0;quickScore=0;quickQs=[];var used={},n=1;while(quickQs.length<12){var q=qmake(quickGrade,quickDiff,n++);if(!used[q.key]){used[q.key]=1;quickQs.push(q)}}$('quickGameTitle').textContent='⚡ '+quickGrade+'° · '+DIFF[quickDiff][0];show('quickGame');renderQuick()}
function renderQuick(){var q=quickQs[quickPos];$('quickGameProgress').textContent='Reto '+(quickPos+1)+' de 12 · '+quickScore+' aciertos';$('quickQuestion').textContent=q.text;$('quickFeedback').textContent='';$('quickNext').style.display='none';$('quickOptions').innerHTML=q.options.map(function(v){return '<button class="answer quickOpt" data-a="'+v+'">'+v+'</button>'}).join('');document.querySelectorAll('.quickOpt').forEach(function(b){b.onclick=function(){document.querySelectorAll('.quickOpt').forEach(function(x){x.disabled=true});if(b.dataset.a===q.answer){quickScore++;S.xp+=8;S.coins+=2;S.materials++;b.classList.add('correct');$('quickFeedback').textContent='✅ ¡Correcto! +1 material'}else{$('quickFeedback').textContent='❌ Era '+q.answer;b.classList.add('wrong')}save();$('quickNext').style.display='block';$('quickNext').textContent=quickPos===11?'🏁 Resultado':'➡️ Siguiente'}})})}
function mentalGrades(){var h='';for(var g=1;g<=11;g++)h+='<button class="grade" data-g="'+g+'"><b>🧠 '+g+'° grado</b><span>'+Math.min(7,3+Math.floor((g-1)/3))+' números</span></button>';$('mentalGradeGrid').innerHTML=h;document.querySelectorAll('#mentalGradeGrid .grade').forEach(function(b){b.onclick=function(){startMental(+b.dataset.g)}});show('mentalMath')}
function startMental(g){mentalGrade=g;clearInterval(mentalTimer);var len=Math.min(7,3+Math.floor((g-1)/3));mentalNumbers=[];for(var i=0;i<len;i++)mentalNumbers.push(rand(1,g<=3?9:g<=6?20:100));$('mentalSetup').style.display='none';$('mentalRound').style.display='block';$('mentalAnswer').value='';$('mentalFeedback').textContent='';$('mentalCheck').disabled=true;var i=0;mentalTimer=setInterval(function(){if(i<len)$('mentalSequence').textContent=mentalNumbers[i++];else{clearInterval(mentalTimer);$('mentalSequence').textContent='❓';$('mentalCountdown').textContent='🧠 ¡Calcula!';$('mentalCheck').disabled=false}},Math.max(350,900-g*35))}
$('quickChallengesBtn').onclick=renderQuickGrades;$('mentalMathBtn').onclick=mentalGrades;$('backQuickChallenges').onclick=function(){show('explore')};$('backQuickDifficulty').onclick=renderQuickGrades;$('backQuickGame').onclick=renderQuickDiff;$('quickNext').onclick=function(){if(quickPos===11){S.xp+=quickScore*6;S.coins+=quickScore;save();celebrate('⚡ ¡Reto terminado!','Aciertos: '+quickScore+'/12.','quickDifficulty')}else{quickPos++;renderQuick()}};$('backMentalMath').onclick=function(){clearInterval(mentalTimer);$('mentalRound').style.display='none';$('mentalSetup').style.display='block';show('explore')};$('mentalCheck').onclick=function(){var a=Number($('mentalAnswer').value),sum=mentalNumbers.reduce(function(x,y){return x+y},0);$('mentalCheck').disabled=true;$('mentalFeedback').textContent=a===sum?'✅ ¡Excelente! Resultado: '+sum:'❌ Resultado correcto: '+sum;S.xp+=a===sum?25:5;if(a===sum)S.coins+=5;save();setTimeout(function(){startMental(mentalGrade)},900)};
'''
s=s.replace("$('themeBtn').onclick=function(){",js+"$('themeBtn').onclick=function(){",1)
s=s.replace("else if(n==='exploreDifficulty'){renderExploreDifficulty()}else{renderLevels();show('levels')}","else if(n==='exploreDifficulty'){renderExploreDifficulty()}else if(n==='quickDifficulty'){renderQuickDiff()}else{renderLevels();show('levels')}",1)
p.write_text(s,encoding='utf-8')